# iOS template, see monorepo/Templates
#
# Version: 1

stages:
  - test
  - build

before_script:
  - git status
  - echo $CI_PROJECT_PATH
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US.UTF-8
  - export LC_ALL=en_US.UTF-8
  - export FASTLANE_SKIP_UPDATE_CHECK=1
  - gem install bundle
  - bundle install

after_script:
  - git status

test:
  stage: test
  tags:
    - ios
  script:
    - bundle exec fastlane tests

build:
  stage: build
  only:
    - master
  tags:
    - ios
  script:
    - bundle exec fastlane build
