# iOS template, see monorepo/Templates
#
# Version: 2

disabled_rules:
  - trailing_whitespace

excluded:
  - Vendor

# Justification: Nesting types reads better at call site, eg: Constants.Files.Preview.url
nesting:
  type_level: 3

# Justification: What the heck is the point in this not being the default!?!
line_length:
  ignores_urls: true
  ignores_comments: true
