os:
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9.2

script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      swift -version;
      xcodebuild -version;
      xcodebuild -showsdks;
      fastlane tests
    fi
