os:
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9.2

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      gem install bundle
      bundle install
    fi

script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      swift -version;
      xcodebuild -version;
      xcodebuild -showsdks;
      bundle exec fastlane tests
    fi
